[package]
name = "bafomet"
version = "0.1.0"
description = "A BFT SMR library in Rust!"
authors = ["Tiago Carvalho <sugoiuguu@tfwno.gf>"]
edition = "2021"
license = "MIT"
homepage = "https://github.com/sug0/bafomet"
repository = "https://github.com/sug0/bafomet"
documentation = "https://docs.rs/bafomet"
readme = "README.md"

[features]
default = [
    "async_runtime_tokio",
    "threadpool_crossbeam",
    "socket_tokio_tcp",
    "serialize_serde",
    "channel_futures_mpsc",
    "crypto_signature_ring_ed25519",
    "crypto_hash_blake3_blake3",
    "collections_randomstate_twox_hash"
]

socket_tokio_tcp = ["tokio", "tokio-util"]
socket_async_std_tcp = ["async-std"]
socket_rio_tcp = ["rio", "socket2"]

serialize_serde = ["serde", "serde-big-array", "serde_bytes"]

async_runtime_tokio = ["tokio"]
async_runtime_async_std = ["async-std"]

crypto_signature_ring_ed25519 = ["ring"]
crypto_hash_ring_sha2 = ["ring"]
crypto_hash_blake3_blake3 = ["blake3"]

threadpool_crossbeam = ["threadpool-crossbeam-channel"]
threadpool_cthpool = ["cthpool"]

channel_futures_mpsc = []
channel_flume_mpmc = ["flume"]
channel_async_channel_mpmc = ["async-channel"]

collections_randomstate_std = []
collections_randomstate_twox_hash = ["twox-hash"]

#bench = ["expose_impl", "oneshot", "futures-timer", "async-semaphore"]
expose_impl = []

[build-dependencies]
itertools = "0.9"

[dev-dependencies]
bincode = "1"
num_cpus = "1"

[dependencies]
#scopeguard = "1"
intmap = "0.7"
either = "1"
oneshot = "0.1"
futures = "0.3"
futures-timer = "3"
async-tls = "0.11"
rustls = "0.19"
parking_lot = "0.11"
#subtle = "2"
linked-hash-map = "0.5"
rand_core = { version = "0.6", features = ["getrandom"] }
smallvec = { version = "1", features = ["union", "write"] }
async-std = { version = "1", optional = true }
tokio = { version = "1", features = ["full"], optional = true }
tokio-util = { version = "0.6", features = ["compat"], optional = true }
ring = { version = "0.16", optional = true }
threadpool-crossbeam-channel = { version = "1", optional = true }
#async-semaphore = { version = "1", optional = true }
serde = { version = "1", features = ["derive"], optional = true }
serde-big-array = { version = "0.3", optional = true }
cthpool = { git = "https://github.com/sug0/cthpool", optional = true }
rio = { version = "0.9", optional = true }
socket2 = { version = "0.4", optional = true }
blake3 = { version = "0.3", optional = true }
flume = { version = "0.10", optional = true }
async-channel = { version = "1", optional = true }
twox-hash = { version = "1", optional = true }
serde_bytes = { version = "0.11", optional = true }
